services: 
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: lait
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: subscription_db
    ports:
      - "5432:5432" 

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: